name: Metrics
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Github stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: stats.svg
          user: ValentinH
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_display: regular
          config_timezone: Europe/Paris
          # traffic
          plugin_traffic: yes
          # pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          # reactions
          plugin_reactions: yes
          plugin_reactions_limit: 200 # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100 # Compute reactions over laste 100 issues/pull requests opened
          plugin_reactions_days: 30 # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot # Ignore "bot" user
          # stargazers charts
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist