name: Metrics
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Github stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: stats.svg
          user: ValentinH
          template: classic
          base: header, activity, repositories, metadata
          base_indepth: true
          config_display: regular
          config_timezone: Europe/Paris
          # traffic
          plugin_traffic: yes
          # reactions
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_details: count # Display reactions count
          plugin_reactions_ignored: bot # Ignore "bot" user
          # stargazers charts
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist